version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-appdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ./volumes/ollama:/root/.ollama
    networks:
      - backend
    restart: unless-stopped

  telegram-bot:
    image: ${TELEGRAM_BOT_IMAGE:-bot-spese-telegram:dev}
    container_name: telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_NAME=${BOT_NAME:-RADQ Expenses Tracker}
      - BOT_SHORT_DESCRIPTION=${BOT_SHORT_DESCRIPTION:-Track expenses easily with RADQ.}
      - BOT_DESCRIPTION=${BOT_DESCRIPTION:-A simple expenses tracker bot. Use /help to see commands.}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5:0.5b}
      - OLLAMA_PULL_ON_START=${OLLAMA_PULL_ON_START:-true}
    depends_on:
      - postgres
      - ollama
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
